backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    folder: content/news
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Enabled', name: 'enabled', widget: 'boolean' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'members'
    label: 'Members'
    folder: 'content/members'
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Enabled', name: 'enabled', widget: 'boolean', default: 'true', required: true }
      - { label: 'Officer', name: 'officer', widget: 'boolean', default: 'false', required: true }
      - { label: 'Officer Title', name: 'officer-title', widget: 'string' }
      - { label: 'Race', name: 'race', widget: 'select', options: ['Human', 'Night Elf', 'Gnome', 'Dwarf', 'Draeni'], required: true }
      - { label: 'Class', name: 'class', widget: 'select', options: ['Druid', 'Hunter', 'Mage', 'Paladin', 'Priest', 'Rogue', 'Shaman', 'Warlock', 'Warrior'], required: true }
      - { label: 'Picture', name: 'picture', widget: 'image', required: true }
    
      